const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {chromium}=require('playwright');

const edge='C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe';
if(!fs.existsSync(edge)){console.log('Edge unavailable; tutorial browser test skipped');process.exit(0);}
const root=path.resolve(__dirname,'..');
const file=name=>'file:///'+path.join(root,name).replace(/\\/g,'/');
(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:edge});
  try{
    const page=await browser.newPage({viewport:{width:1280,height:800}});
    await page.goto(file('tutorial-broadcast.html'));
    assert.match(await page.title(),/廣播切換畫面.*Scratch/);
    assert.equal(await page.locator('svg[role=img]').count(),1);
    assert.equal(await page.locator('.scratchblocks svg.scratchblocks-style-scratch3').count(),30,'every route should render Scratch 3 sender and receiver blocks');
    assert.match(await page.locator('main').innerText(),/只輸入流程圖中的英文代碼/);
    assert.deepEqual(await page.evaluate(()=>Object.values(screenCodes)),['HOME','MENU','L1_INFO','L1_PLAY','L1_DONE','L2_INFO','L2_PLAY','L2_DONE','END']);
    assert.doesNotMatch(await page.locator('main').innerText(),/分數超過|門檻可改/);
    assert.equal(await page.locator('.route-demo-button').count(),6);
    assert.equal(await page.evaluate(()=>Object.values(screens).reduce((count,screen)=>count+screen.buttons.length,0)),11);
    assert.match(await page.locator('#flow').innerText(),/12 個用途/);
    assert.equal(await page.locator('.inventory tbody tr').count(),9);
    for(const name of ['標題首頁','關卡選擇','第一關任務說明','第一關遊玩','第一關完成','第二關任務說明','第二關遊玩','第二關完成','最後一頁']){
      assert.match((await page.locator('#flow').innerText()).replace(/\s+/g,''),new RegExp(name));
      assert.match(await page.locator('.route-grid').innerText(),new RegExp(name));
    }
    assert.equal(await page.getByText('四年級版').count(),0);
    assert.match(await page.locator('main').innerText(),/標題首頁/);
    assert.equal(await page.locator('#screen-title').innerText(),'標題首頁');
    await page.locator('.route-demo-button[data-go="intro1"]').click();
    assert.equal(await page.locator('#screen-title').innerText(),'第一關任務說明');
    await page.locator('#demo-reset').click();
    assert.equal(await page.locator('#screen-title').innerText(),'標題首頁');
    await page.locator('#screen-actions button').filter({hasText:'開始'}).click();
    assert.equal(await page.locator('#screen-title').innerText(),'關卡選擇');
    await page.locator('#screen-actions button').filter({hasText:'第一關'}).click();
    assert.equal(await page.locator('#screen-title').innerText(),'第一關任務說明');
    await page.locator('#menu-button').click();
    assert.equal(await page.locator('#screen-title').innerText(),'關卡選擇');
    await page.locator('#screen-actions button').filter({hasText:'第二關'}).click();
    assert.equal(await page.locator('#screen-title').innerText(),'第二關任務說明');
    await page.locator('#menu-button').click();
    await page.locator('#screen-actions button').filter({hasText:'第一關'}).click();
    await page.locator('#screen-actions button').filter({hasText:'開始第一關'}).click();
    assert.equal(await page.locator('#screen-title').innerText(),'第一關遊玩');
    assert.equal(await page.locator('#screen-actions button').count(),0,'first level should not need a completion button');
    await page.locator('#screen-title').filter({hasText:'第一關完成'}).waitFor({timeout:5000});
    assert.equal(await page.locator('#screen-title').innerText(),'第一關完成');
    await page.locator('#screen-actions button').filter({hasText:'再玩第一關'}).click();
    assert.equal(await page.locator('#screen-title').innerText(),'第一關遊玩');
    await page.locator('#screen-title').filter({hasText:'第一關完成'}).waitFor({timeout:5000});
    await page.locator('#screen-actions button').filter({hasText:'前往第二關'}).click();
    assert.equal(await page.locator('#screen-title').innerText(),'第二關任務說明');
    await page.locator('#screen-actions button').filter({hasText:'開始第二關'}).click();
    assert.equal(await page.locator('#screen-title').innerText(),'第二關遊玩');
    assert.equal(await page.locator('#screen-actions button').count(),0,'second level should not need a completion button');
    await page.locator('#screen-title').filter({hasText:'第二關完成'}).waitFor({timeout:5000});
    assert.equal(await page.locator('#screen-title').innerText(),'第二關完成');
    await page.locator('#menu-button').click();
    assert.equal(await page.locator('#screen-title').innerText(),'關卡選擇');
    await page.locator('#screen-actions button').filter({hasText:'第二關'}).click();
    await page.locator('#screen-actions button').filter({hasText:'開始第二關'}).click();
    await page.locator('#screen-title').filter({hasText:'第二關完成'}).waitFor({timeout:5000});
    await page.locator('#screen-actions button').filter({hasText:'再玩第二關'}).click();
    assert.equal(await page.locator('#screen-title').innerText(),'第二關遊玩');
    await page.locator('#screen-title').filter({hasText:'第二關完成'}).waitFor({timeout:5000});
    await page.locator('#screen-actions button').filter({hasText:'前往最後一頁'}).click();
    assert.equal(await page.locator('#screen-title').innerText(),'最後一頁');
    await page.locator('#screen-actions button').filter({hasText:'回關卡選擇'}).click();
    assert.equal(await page.locator('#screen-title').innerText(),'關卡選擇');
    assert.equal(await page.locator('.check input').count(),5);
    for(const box of await page.locator('.check input').all())await box.check();
    assert.match(await page.locator('#check-result').innerText(),/回網站勾選「關卡以廣播串接」/);
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'mobile viewport should not horizontally overflow');
    await page.goto(file('index.html'));
    await page.locator('#liGuest').click();
    await page.locator('#group').selectOption('game');
    await page.locator('[data-tab=feat]').click();
    const link=page.locator('a[href="tutorial-broadcast.html?v=3.8"]');
    assert.equal(await link.count(),1);
    assert.equal(await link.getAttribute('target'),'_blank');
    assert.match(await link.locator('..').innerText(),/關卡以廣播串接/);
    assert(!await link.innerText().then(text=>text.includes('四年級')));
    console.log('Broadcast routing, flowchart terms, Scratch 3 blocks, checklist, responsive layout and main-site link passed');
  }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exit(1);});
