const assert=require('node:assert/strict');
const path=require('node:path');
const {chromium}=require('playwright');
(async()=>{
 const b=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
 try{
  const p=await b.newPage({viewport:{width:390,height:844}});
  const errors=[];p.on('pageerror',e=>errors.push(e.message));
  await p.goto('file:///'+path.resolve(__dirname,'..','tutorial-collaboration.html').replace(/\\/g,'/'));
  assert.equal(await p.locator('.full-reference').getAttribute('open'),null);
  assert.equal(await p.locator('.player-check').count(),2);
  assert.equal(await p.locator('.journey').count(),0);
  await p.locator('#player-one-check input').first().check();
  assert.equal(await p.locator('#player-two-check input').first().isChecked(),false);
  assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);
  await p.locator('.shared-check>details>summary').click();
  const go=async to=>p.locator(`[data-scene="${to}"]`).click();
  await go('menu');await go('1說明');await go('menu');await go('1說明');await go('1遊戲');
  assert.equal(await p.locator('[data-scene]').count(),0);
  await p.locator('#sim-screen code').filter({hasText:'1完成'}).waitFor();
  await go('2說明');await go('2遊戲');
  await p.locator('#sim-screen code').filter({hasText:'2完成'}).waitFor();
  await go('2遊戲');await p.locator('#sim-screen code').filter({hasText:'2完成'}).waitFor();
  await go('成果');await go('open');
  assert.ok(await p.locator('.single-checks a[href="collaboration-checklist.html"]').count());
  await p.locator('.full-reference>summary').click();
  assert.equal(await p.locator('#naming-table tbody tr').count(),9);
  assert.equal(await p.locator('svg .sb3-obsolete').count(),0);
  const download=p.waitForEvent('download');await p.locator('#wiring-download').click();
  assert.equal((await download).suggestedFilename(),'接線表.txt');
  await p.locator('.full-reference>summary').click();
  await p.setViewportSize({width:1280,height:1000});
  await p.evaluate(()=>scrollTo(0,0));await p.waitForTimeout(500);
  await p.screenshot({path:'D:/codex/資訊團隊/合作圖解首頁.png'});
  await p.locator('.single-checks').scrollIntoViewIfNeeded();
  await p.screenshot({path:'D:/codex/資訊團隊/合作圖解交付.png'});
  assert.deepEqual(errors,[]);
  console.log('Single-page player checklists, mobile layout, routing, replay and downloads passed');
 }finally{await b.close();}
})().catch(e=>{console.error(e);process.exit(1)});
